// <auto-generated />
using System;
using GradingSystem.Services.Submissions.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GradingSystem.Services.Submissions.Api.Migrations
{
    [DbContext(typeof(SubmissionsDbContext))]
    [Migration("20251118060000_AddSubmissionProcessingEntities")]
    partial class AddSubmissionProcessingEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GradingSystem.Services.Submissions.Api.Data.SubmissionAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SubmissionEntryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionEntryId");

                    b.ToTable("SubmissionAssets", (string)null);
                });

            modelBuilder.Entity("GradingSystem.Services.Submissions.Api.Data.SubmissionBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("SubmissionFileId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("SubmissionFileId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("SubmissionBatches", (string)null);
                });

            modelBuilder.Entity("GradingSystem.Services.Submissions.Api.Data.SubmissionEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExtractedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SubmissionBatchId")
                        .HasColumnType("integer");

                    b.Property<string>("TextHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal?>("TemporaryScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("StudentCode");

                    b.HasIndex("SubmissionBatchId");

                    b.HasIndex("TextHash")
                        .IsUnique();

                    b.ToTable("SubmissionEntries", (string)null);
                });

            modelBuilder.Entity("GradingSystem.Services.Submissions.Api.Data.SubmissionFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SubmissionFiles", (string)null);
                });

            modelBuilder.Entity("GradingSystem.Services.Submissions.Api.Data.SubmissionViolation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetLink")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<int?>("SubmissionAssetId")
                        .HasColumnType("integer");

                    b.Property<int>("SubmissionEntryId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionAssetId");

                    b.HasIndex("SubmissionEntryId");

                    b.ToTable("SubmissionViolations", (string)null);
                });

            modelBuilder.Entity("GradingSystem.Services.Submissions.Api.Data.SubmissionAsset", b =>
                {
                    b.HasOne("GradingSystem.Services.Submissions.Api.Data.SubmissionEntry", "SubmissionEntry")
                        .WithMany("Assets")
                        .HasForeignKey("SubmissionEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubmissionEntry");
                });

            modelBuilder.Entity("GradingSystem.Services.Submissions.Api.Data.SubmissionBatch", b =>
                {
                    b.HasOne("GradingSystem.Services.Submissions.Api.Data.SubmissionFile", "SubmissionFile")
                        .WithMany()
                        .HasForeignKey("SubmissionFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubmissionFile");
                });

            modelBuilder.Entity("GradingSystem.Services.Submissions.Api.Data.SubmissionEntry", b =>
                {
                    b.HasOne("GradingSystem.Services.Submissions.Api.Data.SubmissionBatch", "SubmissionBatch")
                        .WithMany("Entries")
                        .HasForeignKey("SubmissionBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubmissionBatch");
                });

            modelBuilder.Entity("GradingSystem.Services.Submissions.Api.Data.SubmissionViolation", b =>
                {
                    b.HasOne("GradingSystem.Services.Submissions.Api.Data.SubmissionAsset", "SubmissionAsset")
                        .WithMany("LinkedViolations")
                        .HasForeignKey("SubmissionAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GradingSystem.Services.Submissions.Api.Data.SubmissionEntry", "SubmissionEntry")
                        .WithMany("Violations")
                        .HasForeignKey("SubmissionEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubmissionAsset");

                    b.Navigation("SubmissionEntry");
                });

            modelBuilder.Entity("GradingSystem.Services.Submissions.Api.Data.SubmissionBatch", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("GradingSystem.Services.Submissions.Api.Data.SubmissionAsset", b =>
                {
                    b.Navigation("LinkedViolations");
                });

            modelBuilder.Entity("GradingSystem.Services.Submissions.Api.Data.SubmissionEntry", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Violations");
                });
#pragma warning restore 612, 618
        }
    }
}

