// <auto-generated />
using System;
using GradingSystem.Services.Submissions.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GradingSystem.Services.Submissions.Api.Migrations
{
    [DbContext(typeof(SubmissionsDbContext))]
    partial class SubmissionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GradeEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExaminerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GradedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("SubmissionEntryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExaminerId")
                        .HasDatabaseName("IX_GradeEntries_ExaminerId");

                    b.HasIndex("SubmissionEntryId")
                        .HasDatabaseName("IX_GradeEntries_SubmissionEntryId");

                    b.ToTable("grade_entries", (string)null);
                });

            modelBuilder.Entity("GradingSystem.Services.Submissions.Api.Data.AssignedExaminer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExamId")
                        .HasColumnType("integer");

                    b.Property<int>("ExaminerId")
                        .HasColumnType("integer");

                    b.Property<int?>("SubmissionBatchId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExamId")
                        .HasDatabaseName("IX_AssignedExaminer_ExamId");

                    b.HasIndex("ExaminerId")
                        .HasDatabaseName("IX_AssignedExaminer_ExaminerId");

                    b.HasIndex("SubmissionBatchId")
                        .HasDatabaseName("IX_AssignedExaminer_SubmissionBatchId");

                    b.HasIndex("SubmissionBatchId", "ExaminerId")
                        .HasDatabaseName("IX_AssignedExaminer_Batch_Examiner");

                    b.ToTable("assigned_examiners", (string)null);
                });

            modelBuilder.Entity("GradingSystem.Services.Submissions.Api.Data.CachedExam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SemesterId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("CachedExams", (string)null);
                });

            modelBuilder.Entity("GradingSystem.Services.Submissions.Api.Data.CachedExaminer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CachedExaminers");
                });

            modelBuilder.Entity("GradingSystem.Services.Submissions.Api.Data.CachedSemester", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CachedSemesters", (string)null);
                });

            modelBuilder.Entity("GradingSystem.Services.Submissions.Api.Data.SubmissionAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SubmissionEntryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionEntryId");

                    b.ToTable("SubmissionAssets", (string)null);
                });

            modelBuilder.Entity("GradingSystem.Services.Submissions.Api.Data.SubmissionBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExamId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("SubmissionFileId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("Status");

                    b.HasIndex("SubmissionFileId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("SubmissionBatches", (string)null);
                });

            modelBuilder.Entity("GradingSystem.Services.Submissions.Api.Data.SubmissionEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExtractedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SubmissionBatchId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TemporaryScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("TextHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("StudentCode");

                    b.HasIndex("SubmissionBatchId");

                    b.HasIndex("TextHash")
                        .IsUnique();

                    b.ToTable("SubmissionEntries", (string)null);
                });

            modelBuilder.Entity("GradingSystem.Services.Submissions.Api.Data.SubmissionFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SubmissionFiles", (string)null);
                });

            modelBuilder.Entity("GradingSystem.Services.Submissions.Api.Data.SubmissionViolation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetLink")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<int?>("SubmissionAssetId")
                        .HasColumnType("integer");

                    b.Property<int>("SubmissionEntryId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionAssetId");

                    b.HasIndex("SubmissionEntryId");

                    b.ToTable("SubmissionViolations", (string)null);
                });

            modelBuilder.Entity("GradeEntry", b =>
                {
                    b.HasOne("GradingSystem.Services.Submissions.Api.Data.SubmissionEntry", "SubmissionEntry")
                        .WithMany()
                        .HasForeignKey("SubmissionEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubmissionEntry");
                });

            modelBuilder.Entity("GradingSystem.Services.Submissions.Api.Data.AssignedExaminer", b =>
                {
                    b.HasOne("GradingSystem.Services.Submissions.Api.Data.SubmissionBatch", "SubmissionBatch")
                        .WithMany()
                        .HasForeignKey("SubmissionBatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SubmissionBatch");
                });

            modelBuilder.Entity("GradingSystem.Services.Submissions.Api.Data.SubmissionAsset", b =>
                {
                    b.HasOne("GradingSystem.Services.Submissions.Api.Data.SubmissionEntry", "SubmissionEntry")
                        .WithMany("Assets")
                        .HasForeignKey("SubmissionEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubmissionEntry");
                });

            modelBuilder.Entity("GradingSystem.Services.Submissions.Api.Data.SubmissionBatch", b =>
                {
                    b.HasOne("GradingSystem.Services.Submissions.Api.Data.SubmissionFile", "SubmissionFile")
                        .WithMany()
                        .HasForeignKey("SubmissionFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubmissionFile");
                });

            modelBuilder.Entity("GradingSystem.Services.Submissions.Api.Data.SubmissionEntry", b =>
                {
                    b.HasOne("GradingSystem.Services.Submissions.Api.Data.SubmissionBatch", "SubmissionBatch")
                        .WithMany("Entries")
                        .HasForeignKey("SubmissionBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubmissionBatch");
                });

            modelBuilder.Entity("GradingSystem.Services.Submissions.Api.Data.SubmissionViolation", b =>
                {
                    b.HasOne("GradingSystem.Services.Submissions.Api.Data.SubmissionAsset", "SubmissionAsset")
                        .WithMany("LinkedViolations")
                        .HasForeignKey("SubmissionAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GradingSystem.Services.Submissions.Api.Data.SubmissionEntry", "SubmissionEntry")
                        .WithMany("Violations")
                        .HasForeignKey("SubmissionEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubmissionAsset");

                    b.Navigation("SubmissionEntry");
                });

            modelBuilder.Entity("GradingSystem.Services.Submissions.Api.Data.SubmissionAsset", b =>
                {
                    b.Navigation("LinkedViolations");
                });

            modelBuilder.Entity("GradingSystem.Services.Submissions.Api.Data.SubmissionBatch", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("GradingSystem.Services.Submissions.Api.Data.SubmissionEntry", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Violations");
                });
#pragma warning restore 612, 618
        }
    }
}
